// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Csr {
    Title: string;
    Tiers: { [key: number]: Tier };
}

export interface Tier {
    Title: string;
    Media: Media;
    Image: Image;
}

export interface Image {
    Width:  number;
    Height: number;
}

export interface Media {
    MediaUrl:      string;
    MimeType:      string;
    Caption:       string;
    AlternateText: string;
    FolderPath:    string;
    FileName:      string;
}
