// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface IGameHistoryResponse {
    Start:       number;
    Count:       number;
    ResultCount: number;
    Results:     Result[];
    Links:       Links;
}

export interface Links {
}

export interface Result {
    MatchId:              string;
    MatchType:            number;
    GameMode:             number;
    SeasonId:             null | string;
    PlaylistId:           string;
    Teams:                { [key: string]: Team };
    MapId:                string;
    MatchStartDate:       MatchStartDateClass;
    PlayerMatchDuration:  string;
    PlayerIndex:          number;
    TeamId:               number;
    TeamPlayerIndex:      number;
    LeaderId:             number;
    PlayerCompletedMatch: boolean;
    PlayerMatchOutcome:   number;
    XPProgress:           XPProgress;
    RatingProgress:       RatingProgress;
}

export interface MatchStartDateClass {
    ISO8601Date: string;
}

export interface RatingProgress {
    PreviousCsr: Csr | null;
    UpdatedCsr:  Csr | null;
    PreviousMmr: Mmr;
    UpdatedMmr:  Mmr;
}

export interface Csr {
    Tier:                        number;
    Designation:                 number;
    Raw:                         number;
    PercentToNextTier:           number;
    MeasurementMatchesRemaining: number;
    Rank:                        null;
}

export interface Mmr {
    Rating:           number;
    Variance:         number;
    LastModifiedDate: MatchStartDateClass;
}

export interface Team {
    TeamSize: number;
}

export interface XPProgress {
    PreviousTotalXP:       number;
    GameplayXP:            number;
    ChallengesXP:          number;
    UpdatedTotalXP:        number;
    CompletedSpartanRanks: any[];
    RanksCompleted:        any[];
}
