// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Match {
  MatchId:          string;
  MatchType:        number;
  GameMode:         number;
  SeasonId:         string;
  PlaylistId:       string;
  MapId:            string;
  IsMatchComplete:  boolean;
  MatchEndReason:   number;
  VictoryCondition: number;
  MatchStartDate:   MatchStartDateClass;
  MatchDuration:    string;
  Teams:            { [key: string]: Team };
  Players:          { [key: string]: Player };
  events: any[];
}
export interface PlayerResource { 
  "Supply": number,
  "TotalSupply": number,
  "Energy": number,
  "TotalEnergy": number,
  "Population": number,
  "PopulationCap": number,
  "TechLevel": number,
  "CommandPoints": number,
  "TotalCommandPoints": number,
  "Mana": number,
  "TotalMana": number,
  "ManaRate": number,
  "CommandXP": number
}

export interface ResourceHeartBeat {
  TeamResources:              { [key: string]: TeamResource };
  PlayerResources:            { [key: string]: PlayerResource};
  TimeSinceStartMilliseconds: number;
  EventName:                  string;
}

export interface TeamResource {
  ObjectiveScore: number;
}


export interface MatchStartDateClass {
  ISO8601Date: string;
}

export interface Player {
  IsHuman:              boolean;
  HumanPlayerId:        HumanPlayerID | null;
  ComputerPlayerId:     null;
  ComputerDifficulty:   null;
  TeamId:               number;
  TeamPlayerIndex:      number;
  LeaderId:             number;
  PlayerCompletedMatch: boolean;
  TimeInMatch:          string;
  PlayerMatchOutcome:   number;
  PointStats:           PointStats;
  UnitStats:            { [key: string]: UnitStat };
  CardStats:            Stats;
  WaveStats:            Stats;
  LeaderPowerStats:     { [key: string]: LeaderPowerStat };
  XPProgress:           XPProgress;
  RatingProgress:       RatingProgress;
}

export interface Stats {
}

export interface HumanPlayerID {
  Gamertag: string;
  Xuid:     null;
}

export interface LeaderPowerStat {
  TimesCast: number;
}

export interface PointStats {
  hook_bldg_EnergyCapturePoint_01: HookBldgEnergyCapturePoint01;
}

export interface HookBldgEnergyCapturePoint01 {
  TimesCaptured: number;
}

export interface RatingProgress {
  PreviousCsr: Csr;
  UpdatedCsr:  Csr;
  PreviousMmr: Mmr;
  UpdatedMmr:  Mmr;
}

export interface Csr {
  Tier:                        number;
  Designation:                 number;
  Raw:                         number;
  PercentToNextTier:           number;
  MeasurementMatchesRemaining: number;
  Rank:                        null;
}

export interface Mmr {
  Rating:           number;
  Variance:         number;
  LastModifiedDate: MatchStartDateClass;
}

export interface UnitStat {
  TotalBuilt:     number;
  TotalLost:      number;
  TotalDestroyed: number;
}

export interface XPProgress {
  PreviousTotalXP:       number;
  GameplayXP:            number;
  ChallengesXP:          number;
  UpdatedTotalXP:        number;
  CompletedSpartanRanks: any[];
  RanksCompleted:        any[];
}

export interface Team {
  TeamSize:       number;
  MatchOutcome:   number;
  ObjectiveScore: number;
}
