// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface MmrResposne {
    Results: ResultElement[];
    Links:   Links;
}

export interface Links {
    Self: Self;
}

export interface Self {
    AuthorityId:                              string;
    Path:                                     string;
    QueryString:                              string;
    RetryPolicyId:                            string;
    TopicName:                                string;
    AcknowledgementTypeId:                    number;
    AuthenticationLifetimeExtensionSupported: boolean;
    ClearanceAware:                           boolean;
}

export interface ResultElement {
    Id:         string;
    ResultCode: number;
    Result:     ResultResult;
}

export interface ResultResult {
    Mmr: Mmr;
    Csr: Csr;
}

export interface Csr {
    Tier:                        number;
    Designation:                 number;
    Raw:                         number;
    PercentToNextTier:           number;
    MeasurementMatchesRemaining: number;
    Rank:                        number;
}

export interface Mmr {
    Rating:           number;
    Variance:         number;
    LastModifiedDate: LastModifiedDate;
}

export interface LastModifiedDate {
    ISO8601Date: string;
}
